language: python
dist: xenial

os:
  - linux

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy2.7-5.10.0
  - pypy3.5

env:
  - NUMPY="numpy==1.13.1"
  - NUMPY="numpy==1.14.5"
  - NUMPY="numpy>=1.15"

matrix:
  exclude:
    - python: 3.7
      env: NUMPY="numpy==1.13.1"
    - python: pypy2.7-5.10.0
      env: NUMPY="numpy==1.14.5"
    - python: pypy3.5
      env: NUMPY="numpy==1.14.5"
    - python: pypy2.7-5.10.0
      env: NUMPY="numpy==1.13.1"
    - python: pypy3.5
      env: NUMPY="numpy==1.13.1"

addons:
  apt:
    packages:
      - python-setuptools

script:
  pytest -v tests

install:
  - pip install --upgrade setuptools_scm
  - pip install $NUMPY
  - if [[ $TRAVIS_PYTHON_VERSION = pypy* ]] ; then pip install "numpy<1.16.0" ; fi       # FIXME: pypy bug in numpy
  - python -c 'import numpy; print(numpy.__version__)'
  - pip install "awkward>=0.7.0"
  - python -c 'import awkward; print(awkward.__version__)'
  - pip install pytest pytest-runner
  - pip install --upgrade pyOpenSSL     # for deployment

notifications:
  slack: scikit-hep:b6cgBXwccPoaCNLn5VKFJFVy

deploy:
  provider: pypi
  user: pivarski
  password:
    secure: "Mk4yGAMDB6FpQ78nkCmC9VsJVtDr0SqEUUVbZ1xl6Kd4t90o3xXqYOqjFoQz5yBtXR82pwJZyy6D6Thw5VVzhQ9e/T/wrvGYB+MXYaLUNP6SZIQKOV9gVLQ+SkJV0Db2Z5qUHgPzk9lKzerFphjavvvbcvlJxEjM62MB7395rm0llcgQDxgUV1ZblFTmsAL1o57L+lfUoQrE5MI3fAGn8H4vOdMzrzC8Ff7305fEkzatWAgsCYCgggaC43CuIvpZ2kIQsgZ9GSulyG9ixfYlTM6LlcUqAgF7eNZTi9eHTkc5WHXzF3lCaxHpG12CrCTPOYmVaK0hdeQDldcD1/kVN7Ilf2Talg7NpTjWyh1Wbd3VGrTFwzS2xvRsPrGD5GRwmPJvVtNQzBEg+CNBpgH2LDp/nA7BEktHtU7SBGYRY3ya3EXSXXdJvlIIoXkJws/WzpairFTnxuPrJbjfmf0Db5nNlwDkq26KLrIkSGaKWPR0mmYMrKA5lAJqLClkM5a+WPoBSIFSkKM8MBHvr0pw5PcDHV80Tqf+GgOIL7UOITbhOaSgr8C+Quo6CqBaZ2ay21S2H8ebLfkJZ/G/r2eskPndS/V2TyMha+wXRch9iVnJcrYPdepr5x33WfF3quRb2XptegG0c1aanaYml4jwKKZD054dm5CMvpFNhQOtzug="
  distributions: "sdist bdist_wheel --universal"
  on:
    tags: true
    branch: master
    condition: '$TRAVIS_PYTHON_VERSION = "3.7" && $NUMPY = "numpy>=1.15"'
